version: '3.5'

services:
  db:
    image: postgres:10.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build: ./api
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 9000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/app
      - ./api/vendor/bundle:/app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 9000:9000
    depends_on:
      - db
  web:
    image: nginx:latest
    volumes:
      - ./docker/web/log:/var/log/nginx:z
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf:z
      - ./front/public:/var/www/html:z
    ports:
      - "3000"
  proxy:
    build: ./docker/proxy
    volumes:
        - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:z
        - ./docker/proxy/log:/var/log/nginx:z
    ports:
        - 80:80
    depends_on:
        - 'api'
        - 'web'
volumes:
  postgres-data:
    driver: local